version: '2'
services:
  zookeeper-1:
    container_name: "zookeeper-1"
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper-2:
    container_name: "zookeeper-2"
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper-3:
    container_name: "zookeeper-3"
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-1:
    container_name: "kafka-1"
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-2:
    container_name: "kafka-2"
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-3:
    container_name: "kafka-3"
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
    extra_hosts:
      - "moby:127.0.0.1"

  spring-consumer-1:
    container_name: "spring-consumer-1"
    image: springio/exemplo-consumer
    network_mode: host
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      TOPIC_NAME: "exemplo"
      CONSUMER_GROUP_ID: "consumerGroup1"
      CONTAINER_NAME: "spring-consumer-1"
      APP_PORT: 8081
    extra_hosts:
      - "moby:127.0.0.1"

  spring-consumer-2:
    container_name: "spring-consumer-2"
    image: springio/exemplo-consumer
    network_mode: host
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      CONTAINER_NAME: "spring-consumer-2"
      APP_PORT: 8082
    extra_hosts:
      - "moby:127.0.0.1"

  spring-consumer-3:
    container_name: "spring-consumer-3"
    image: springio/exemplo-consumer
    network_mode: host
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      TOPIC_NAME: "exemplo"
      CONSUMER_GROUP_ID: "consumerGroup1"
      CONTAINER_NAME: "spring-consumer-3"
      APP_PORT: 8083
    extra_hosts:
      - "moby:127.0.0.1"

  spring-consumer-4:
    container_name: "spring-consumer-4"
    image: springio/exemplo-consumer
    network_mode: host
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      TOPIC_NAME: "exemplo"
      CONSUMER_GROUP_ID: "consumerGroup1"
      CONTAINER_NAME: "spring-consumer-4"
      APP_PORT: 8084
    extra_hosts:
      - "moby:127.0.0.1"

  magic:
    image: digitsy/kafka-magic
    container_name: "magic-kafka"
    network_mode: host
    environment:
      KMAGIC_ALLOW_TOPIC_DELETE: "true"
      KMAGIC_ALLOW_SCHEMA_DELETE: "true"

